### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by P4YN-Ki** [NightKosh/Sophisticated-wolves#112]
So Sophisticated Wolves crashes my Dedicated Server after converting a Wolf from The Twilight Forest and bringing it back to the Overworld. I named a wolf Sebastian and my logs keep saying that when a player was spawning in the Overworld something was happening with Sebastian and the server would immediately crash. I'll provide a copy of the logs.

Crash Log 01: https://pastebin.com/cUMm9XnP

Crash Log 02: https://pastebin.com/KBG0Vsd5

I hope someone can shed some light on the problem. I've had to remove the mod from the server which immediately stopped any and all crashes, but also removed everyone's pets, so yeah.

**Comment by P4YN-Ki** [comment]
Forgot to mention,
MC Version: 1.19.2
Forge Version: 43.2.8
SW Version: 4.1.2

**Comment by NightKosh** [comment]
`
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.equals(Object)" because the return value of "sophisticated_wolves.entity.SophisticatedWolf.m_21826_()" is null
	at sophisticated_wolves.entity.SophisticatedWolf.m_7337_(SophisticatedWolf.java:458) ~[Sophisticated_Wolves-1.19.2-4.1.2.jar%23552!/:4.1.2] {re:classloading}
	at com.abdelaziz.canary.common.entity.CanaryEntityCollisions$1$1.computeNext(CanaryEntityCollisions.java:137) ~[canary-mc1.19.2-0.1.10.jar%23391!/:0.1.10] {re:classloading}
	at com.abdelaziz.canary.common.entity.CanaryEntityCollisions$1$1.computeNext(CanaryEntityCollisions.java:94) ~[canary-mc1.19.2-0.1.10.jar%23391!/:0.1.10] {re:classloading}
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar%2372!/:?] {}
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar%2372!/:?] {}
	at com.abdelaziz.canary.common.entity.CanaryEntityCollisions.getEntityWorldBorderCollisions(CanaryEntityCollisions.java:74) ~[canary-mc1.19.2-0.1.10.jar%23391!/:0.1.10] {re:mixin,re:classloading}
	at net.minecraft.world.entity.Entity.canaryCollideMultiAxisMovement(Entity.java:8929) ~[server-1.19.2-20220805.130853-srg.jar%23611!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,pl:mixin:A}
	at net.minecraft.world.entity.Entity.redirect$bdn000$adjustMovementForCollisionsGetEntitiesLater(Entity.java:8840) ~[server-1.19.2-20220805.130853-srg.jar%23611!/:?] 
`

**Comment by P4YN-Ki** [comment]
Is there anything I can do with the settings oF SW or Canary to resolve this issue, even if only temp?

**Comment by venomouspetal** [comment]
I'm also getting this same crash with minecraft and SW versions the same, but on forge 43.2.3

**Comment by venomouspetal** [comment]
> Is there anything I can do with the settings oF SW or Canary to resolve this issue, even if only temp?

For a temporary fix, I went into the world save, located the entity causing the crash and deleted it.

**Comment by NightKosh** [comment]
Try new version please. 

https://legacy.curseforge.com/minecraft/mc-mods/sophisticated-wolves/files/4627162
