### ISSUE TITLE
Invisible sophisticated wolves.

### ISSUE THREAD

**Issue by DanTheColoradan** [NightKosh/Sophisticated-wolves#14]
I can't tell exactly when it happened, but sometime during installing SecurityCraft, Sophisticated wolves disappeared. I very much doubt it is related to SecurityCraft. Instead, I'm guessing something happened when I made a backup of the world and then ran that backup.

Regular wolves are still visible as are regular tame wolves. As soon as I make them sophisticated they disappear. No errors appear in the log. I've also tried to set the config to _not_ use custom textures, but they still didn't show up. Same thing occurs when I use a s.w. spawn egg.

Any ideas? Or how can I help debug this issue?

**Comment by NightKosh** [comment]
Can you reproduce it on another world?

**Comment by DanTheColoradan** [comment]
Tried it on a new world with a spawn egg and only SW mod. And yes, they are either invisible, or not there. I also tried a regular wolf and it spawns normally.

When I do a spawn egg, they don't seem to spawn at all. I don't hear barking or growling when I spawn a creeper next to that position. When I spawn a normal wolf and use a treat to make it sophisticated, it turns invisible but I can hear it growling.

I'm using a docker container. Here is the command I ran:

`sudo docker run -it -d -p 25566:25565 --name=mc_test -e EULA=TRUE -v /mnt/raid/config/mc_test/:/data -e UID=1003 -e TYPE=FORGE -e FORGEVERSION=11.14.3.1450 -e SEED=-1339183346 -e 'JVM_OPTS=-Xmx2048M -Xms1024M'  itzg/minecraft-server`

**Comment by lcherbst** [comment]
I have run into the same problem on a newly modded server. It was a vanilla server and I had 6 tame wolves. I fed them dog treats to change them into sophisticated wolves and each turned invisible when I gave them a treat. I could hear them follow me and bark, but could not see them. Normal wolves are still visible. This server is also modded with SecurityCraft. I will try to remove SecurityCraft and see if the sophisticated wolves become visible. I'll let you know what I find.

**Comment by lcherbst** [comment]
I removed SecurityCraft from my server and the Sophisticated Wolves became visible. I would rather have sophisticated wolves than security craft, so I will keep SC off my server. BTW, I think sophisticated wolves is one of the best mods out there. Is it possible to add a feature where you could change the ownership of a wolf? I play on a private server with my two sons and I have 6 wolves. I would like to be able to give my sons a couple wolves each. Of course, with sophisticated wolves installed, they have a better chance at finding their own now anyway.

**Comment by DanTheColoradan** [comment]
Very odd. Perhaps @Geforce132 might be able to shed some light on this?

**Comment by DanTheColoradan** [comment]
Honestly, I have no idea what is going on. I've created a 'clean' server directory (rm -r *) and then I just add the SW mod, but still, they won't spawn with the egg and the treat isn't doing anything anymore. Perhaps my dot files? I'll try that next, but I have doubts.

@Geforce132, if you get the chance to let us know if you've seen a similar problem, please do comment. Otherwise, @NightKosh, if your server is working fine, it might help to know what specs you are running. I tried it with (f = forge) 11.14.1.1336, and the latest recommended f 11.14.3.1502 and bleeding edge f 11.14.3.1450 and nothing has fixed it. I've also downloaded the source and looked for errors using IntelliJ, and I'm so far not seeing anything.

It's frustrating for me mostly because the log isn't outputting anything, so I have no idea what is conflicting. Is there a more verbose mode? Perhaps I should alter the source and add some debug info.

**Comment by Geforce132** [comment]
I have no idea what would cause SecurityCraft to mess up SW, it doesn't modify any entities at all. :(

Don't know if this would help, but what version of SecurityCraft and SW are you using?

**Comment by lcherbst** [comment]
I was using SecurityCraft 1.7.4.1 and SophisticatedWolves 3.5.0 when I encountered the problem.

**Comment by NightKosh** [comment]
I made few tests on my home PC trying to inspect this problem..
1) It works fine with any version of forge(without SecurityCraft)
2) It can't be reproduced on local(not server) world
3) Like @lcherbst said wolves become visible when SecurityCraft has been removed.

To be honest, I saw similar problem before, when tried to equip horses' armor on undead horse(it used minecraft code for rendering) - every time armor was equipped horse become invisible...
But I have no idea what happens with wolves...

**Comment by NightKosh** [comment]
I got those error when tried to convert vanilla wolf to sophisticated wolf..
```
[17:10:00] [Client thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.freeforums.geforce.securitycraft.entity.EntityTnTCompact cannot be cast to net.minecraft.entity.EntityLivingBase
java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.freeforums.geforce.securitycraft.entity.EntityTnTCompact cannot be cast to net.minecraft.entity.EntityLivingBase
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.7.0_75]
	at java.util.concurrent.FutureTask.get(FutureTask.java:188) ~[?:1.7.0_75]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1019) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:345) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
Caused by: java.lang.ClassCastException: org.freeforums.geforce.securitycraft.entity.EntityTnTCompact cannot be cast to net.minecraft.entity.EntityLivingBase
	at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnMob(NetHandlerPlayClient.java:817) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_180721_a(S0FPacketSpawnMob.java:120) ~[S0FPacketSpawnMob.class:?]
	at net.minecraft.network.play.server.S0FPacketSpawnMob.processPacket(S0FPacketSpawnMob.java:136) ~[S0FPacketSpawnMob.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:18) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[?:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_75]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 11 more
```

**Comment by NightKosh** [comment]
Good news, I found a way to solve this problem! Some how 2 entities used the same id..
so it is just required to change "entities registration" from
```java
EntityRegistry.registerGlobalEntityID
```
to 
```java
EntityRegistry.registerModEntity
```

**Comment by DanTheColoradan** [comment]
Nice work :+1: tested it and going great so far.

**Comment by CovertJaguar** [comment]
We are experiencing the same issue on 1.10.2, but without SecurityCraft.

**Comment by NightKosh** [comment]
@CovertJaguar could you please post list of mods you are using?

**Comment by CovertJaguar** [comment]
https://dl.dropboxusercontent.com/u/38558957/Minecraft/modpack-2017-04-14.zip

**Comment by NightKosh** [comment]
@CovertJaguar unfortunately I can't reproduce this issue. May be you could give me some additional tips about this problem?

**Comment by CovertJaguar** [comment]
I'm not really sure, between the invisible wolves and the whole screen for all players on the server turning very red whenever a wolf got hurt, we were forced to remove it.

**Comment by NightKosh** [comment]
Sadly, but result of all tests is the same...

**Comment by CovertJaguar** [comment]
Did you try with the dedicated server / client setup using the pack I provided? It worked fine in single player.

**Comment by NightKosh** [comment]
@CovertJaguar Yes, I did. But the result was the same.

**Comment by NightKosh** [comment]
@CovertJaguar I got the same(or similar) issue on 1.11.2 client, with another set of mods. Unfortunately there weren't any errors in logs. And I'm still not sure about stable way to reproduce this problem. 
I created an own issue for this problem #35
