### ISSUE TITLE
Crash when near creeper (1.10)

### ISSUE THREAD

**Issue by bondgb** [NightKosh/Sophisticated-wolves#22]
Hi, I'm using this mod on 1.10 and it works fine except for a crash when a wolf is next to a creeper.

```
java.lang.NoSuchMethodError: net.minecraft.pathfinding.Path.func_75880_b(Lnet/minecraft/util/math/Vec3d;)Z
	at sophisticated_wolves.entity.ai.EntityAIAvoidCreeper.func_75250_a(EntityAIAvoidCreeper.java:92)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2190)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
	at net.minecraft.entity.passive.EntityWolf.func_70636_d(SourceFile:208)
	at sophisticated_wolves.entity.EntitySophisticatedWolf.func_70636_d(EntitySophisticatedWolf.java:201)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.EntityWolf.func_70071_h_(SourceFile:223)
	at sophisticated_wolves.entity.EntitySophisticatedWolf.func_70071_h_(EntitySophisticatedWolf.java:270)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at sophisticated_wolves.entity.ai.EntityAIAvoidCreeper.func_75250_a(EntityAIAvoidCreeper.java:92)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2190)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
	at net.minecraft.entity.passive.EntityWolf.func_70636_d(SourceFile:208)
	at sophisticated_wolves.entity.EntitySophisticatedWolf.func_70636_d(EntitySophisticatedWolf.java:201)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.EntityWolf.func_70071_h_(SourceFile:223)
	at sophisticated_wolves.entity.EntitySophisticatedWolf.func_70071_h_(EntitySophisticatedWolf.java:270)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Entity being ticked --
Details:
	Entity Type: SophisticatedWolves.SWWolf (sophisticated_wolves.entity.EntitySophisticatedWolf)
	Entity ID: 69421
	Entity Name: entity.SophisticatedWolves.SWWolf.name
	Entity's Exact location: 1364.50, 4.00, 375.50
	Entity's Block location: World: (1364,4,375), Chunk: (at 4,0,7 in 85,23; contains blocks 1360,0,368 to 1375,255,383), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: New World 2356467
	All players: 1 total; [EntityPlayerMP['bsgb'/28, l='New World 2356467', x=1364.50, y=4.00, z=373.50]]
	Chunk stats: ServerChunkCache: 733 Drop: 0
	Level seed: 5899626801706537583
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (1373,4,383), Chunk: (at 13,0,15 in 85,23; contains blocks 1360,0,368 to 1375,255,383), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Level time: 392 game time, 392 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 109751 (now: false), thunder time: 88237 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

I know 1.10 probably isn't supported by you but I thought I'd let you know anyway.

**Comment by NightKosh** [comment]
Never mind it can be compatible with 1.10. )) Ok. I'll update it soon.
