### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Kehaan** [NightKosh/Sophisticated-wolves#25]
I dont know what caused this crash, but thought i would report it :)

[crash-2016-11-27_16.52.17-server.txt](https://github.com/NightKosh/Sophisticated-wolves/files/614811/crash-2016-11-27_16.52.17-server.txt)

**Comment by NightKosh** [comment]
```
java.lang.NullPointerException: Ticking entity
	at sophisticated_wolves.entity.ai.EntityAINewFollowOwner.func_75253_b(EntityAINewFollowOwner.java:42)
	at net.minecraft.entity.ai.EntityAITasks.func_75773_a(SourceFile:136)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:108)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
	at net.minecraft.entity.passive.EntityWolf.func_70636_d(SourceFile:208)
	at sophisticated_wolves.entity.EntitySophisticatedWolf.func_70636_d(EntitySophisticatedWolf.java:201)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.EntityWolf.func_70071_h_(SourceFile:223)
	at sophisticated_wolves.entity.EntitySophisticatedWolf.func_70071_h_(EntitySophisticatedWolf.java:270)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NightKosh** [comment]
Try latest vesrion - 3.6.4. It should be fixed
