### ISSUE TITLE
The modid SophisticatedWolves is not the same as it's lowercase version.

### ISSUE THREAD

**Issue by leagris** [NightKosh/Sophisticated-wolves#30]
### Versions

* SophisticatedWolves 3.6.5
* Minecraft Forge 13.20.0.2282

> Lowercasing will be enforced in 1.11

It is

### Log extact

```Log
Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
        at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:90) [ModContainerFactory.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:106) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:414) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:554) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: The modid SophisticatedWolves is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
```

**Comment by NightKosh** [comment]
Which version of Minecraft are you used? 1.10.2 ? Any way game should work correctly in 1.10.2 even if id isn't in lowercase.

**Comment by leagris** [comment]
1.11

**Comment by NightKosh** [comment]
Are you sure you use 1.11.2 version of the mod? It has lowercased id since 1.11

**Comment by leagris** [comment]
Whoopsy!

Thank you for your good clue.

| Orign | jar name | md5 |
|:------|:---------|:----|
| [Installed](http://rawgit.com/Beyond-Reality/Beyond-Realty-Farscapes/master/modlist.html#mod-sophisticated-wolves) | `SophisticatedWolves-3.6.jar` | `1c48f88ac1d615c322659c8c8ddc6466` |
| [Curseforge](https://minecraft.curseforge.com/projects/sophisticated-wolves/files/2404567) | `SophisticatedWolves-3.6.jar` | `0e252564a14fe4985b1f90f16fd05116` |

Would have been more straightforward with a distinct jar archive name like:
- `SophisticatedWolves-1.10.2-3.6.jar`
and
- `SophisticatedWolves-1.11.2-3.6.jar`

**Comment by NightKosh** [comment]
Yes, it is a good sugestion. New version will be marked by minecraft version too.

So can I close this issue?

**Comment by leagris** [comment]
Yes sir :)
