### ISSUE TITLE
Fatal Error upon feeding Soph-Dogs[3.6.5]{1.11.2}

### ISSUE THREAD

**Issue by piks** [NightKosh/Sophisticated-wolves#32]
[puffercrash.txt](https://github.com/NightKosh/Sophisticated-wolves/files/1045557/puffercrash.txt)

Upon feeding a pufferfish to a tamed soph-dog the client crashes giving the error in the supplied log. 

Steps to reproduce:
   create world
   spawn soph dog
   tame
   feed dog pufferfish in survival
note: This crash does not occur while in creative only survival

**Comment by NightKosh** [comment]
```
WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.11.2-Recommended.jar)
  FMLPlugin (InventoryTweaks-1.11.2.jar)
  DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 6/1/17 1:14 PM
Description: Unexpected error

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:513)
	at sophisticated_wolves.entity.EntitySophisticatedWolf.func_184645_a(EntitySophisticatedWolf.java:299)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213)
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1191)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:534)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1509)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:513)
	at sophisticated_wolves.entity.EntitySophisticatedWolf.func_184645_a(EntitySophisticatedWolf.java:299)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213)
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1191)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:534)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1509)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)

```
