### ISSUE TITLE
Carrier not working properly

### ISSUE THREAD

**Issue by mxnmnm** [NightKosh/Sophisticated-wolves#56]
I put a dog in a carrier and I can't get it out.  Thanks to another mod I have installed it shows me the error in a report even though I didn't crash.

https://paste.dimdev.org/kicameruya.mccrash

If you want more info on the other mods in the environment let me know!

**Comment by NightKosh** [comment]
```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/attributestudios/wolfarmor/api/util/Capabilities
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/attributestudios/wolfarmor/api/util/Capabilities
    at sophisticated_wolves.compatibility.CompatibilityWolfArmor.getWolfItems(CompatibilityWolfArmor.java:49)
    at sophisticated_wolves.item.pet_carrier.WolfPetCarrier.setAdditionalData(WolfPetCarrier.java:45)
    at sophisticated_wolves.item.pet_carrier.ItemPetCarrier.onItemUse(ItemPetCarrier.java:128)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:876)
    at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:492)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:739)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more
```

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/sophisticated-wolves/files/2601571
