### ISSUE TITLE
Pet carrier not working

### ISSUE THREAD

**Issue by sergifs** [NightKosh/Sophisticated-wolves#88]
I crafted a few pet carriers but i can't get them to work, I right click or right click + shift on the pet but it just does nothing.

**Comment by sergifs** [comment]
I also have Wolf Armor mod installed and I've noticed this error every time i right click using the pet carrier:

[Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/attributestudios/wolfarmor/api/util/Capabilities
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: com/attributestudios/wolfarmor/api/util/Capabilities
        at sophisticated_wolves.compatibility.CompatibilityWolfArmor.storeWolfItems(CompatibilityWolfArmor.java:21) ~[CompatibilityWolfArmor.class:?]
        at sophisticated_wolves.item.pet_carrier.SophisticatedWolfPetCarrier.getAdditionalData(SophisticatedWolfPetCarrier.java:68) ~[SophisticatedWolfPetCarrier.class:?]
        at sophisticated_wolves.item.pet_carrier.ItemPetCarrier.getPetInfo(ItemPetCarrier.java:80) ~[ItemPetCarrier.class:?]
        at sophisticated_wolves.item.pet_carrier.ItemPetCarrier.func_111207_a(ItemPetCarrier.java:57) ~[ItemPetCarrier.class:?]
        at net.minecraft.item.ItemStack.func_111282_a(ItemStack.java:391) ~[aip.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1220) ~[aed.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1075) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

**Comment by CovertJaguar** [comment]
See https://github.com/satyrnidae/wolfarmor/issues/95

**Comment by NightKosh** [comment]
It looks like wolfarmor was taken over by someone else and its API completely reworked, aren't it?

**Comment by satyrnidae** [comment]
well, the API was reworked at least.  It now uses mixin classes instead of capabilities.  I'll see if I can create a PR

**Comment by satyrnidae** [comment]
Looks like the api isn't needed any more.  PR #90 should fix the issue.
